### ISSUE TITLE
Current built of the `verity` agent is broken

### ISSUE THREAD

**Issue by pruneau628** [ianco/aries-agent-test-harness#360]
Hello

I'm posting on 20211012, but issue probably started on september 30ish

Most certainly due to let's encrypt recent certificate expiration (see https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/), the verity agent build is broken, with the following error:
```
./manage build -a verify
(...)
> ngrok@2.3.0 postinstall /root/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - error downloading binary { Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38) code: 'CERT_HAS_EXPIRED' }
ngrok - install failed, retrying
(...)
```
This can be easily corrected with:
```
$ git diff aries-backchannels/verity/Dockerfile.verity
diff --git a/aries-backchannels/verity/Dockerfile.verity b/aries-backchannels/verity/Dockerfile.verity
index 3c07881..6296f3f 100644
--- a/aries-backchannels/verity/Dockerfile.verity
+++ b/aries-backchannels/verity/Dockerfile.verity
@@ -6,6 +6,7 @@ RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 97080EBDA5
 RUN apt-get update && apt-get install -y \
     net-tools \
     npm \
+    ca-certificates \
     ; exit 0
 
 RUN rm -rf /etc/verity/verity-application/*
~/dev/github.com/hyperledger/aries-agent-test-harness
```
I'm new to the surroundings, so tell me if I need to turn that into a pull request.

**Comment by pruneau628** [comment]
Closed by: https://github.com/hyperledger/aries-agent-test-harness/pull/367
