### ISSUE TITLE
ACA-Py and AFGo-Interop tests are failing on completing connections

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#502]
It appears that all of the acapy-main - afgo-interop tests are failing. A summary of the results from the latest run can always be found here: https://allure.vonx.io/allure-docker-service-ui/projects/acapy-b-afgo/reports/latest

All of the tests seem to fail at the same point -- when checking with Bob on the establishment of the connection between Bob and one of the other agents.  For example, in the DID Exchange tests:

```
Test body
Given we have "2" agents 1 attachment0s
And "Acme" is running with parameters "{"inbound_transports": ["http"], "outbound_transports": ["http"] }"2s 564ms
And "Bob" is running with parameters "{"inbound_transports": ["http"], "outbound_transports": ["http"] }"1s 023ms
ERROR ---> When "Acme" and "Bob" create a new connection5s 769ms
Then the invitation serviceEndpoint should use the "["http"]" protocol scheme
```

The assertion error in the harness is:

```
AssertionError: FAILED SUB-STEP: And "Bob" receives the response
Substep info: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/0023-did-exchange.py", line 376, in step_impl
    requester_url, "did-exchange", requester_connection_id, "completed"
AssertionError

Traceback (of failed substep):
  File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/0023-did-exchange.py", line 376, in step_impl
    requester_url, "did-exchange", requester_connection_id, "completed"

  File "/usr/local/lib/python3.7/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.7/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/0160-connection.py", line 405, in step_impl
    """
  File "/usr/local/lib/python3.7/site-packages/behave/runner.py", line 404, in execute_steps
    assert False, message
```

In the DID Exchange tests, the error has more detail:

```
AssertionError: resp_status 400 is not 200; {"code":2005,"message":"did exchange client - accept exchange request: failed to execute state 'responded': handle inbound request: handle inbound request: failed to create destination: create destination: no service endpoint on didcomm service block in diddoc: \u0026{Context:[https://www.w3.org/ns/did/v1] ID:did:peer:1zQmP37XZkovxEEuvk6mq8TbN8pRj7TorCMZth4rvWP1vjWH VerificationMethod:[{ID:#key-1 Type:Ed25519VerificationKey2018 Controller:#id Value:[200 129 16 160 162 169 62 155 40 146 165 154 66 226 43 92 206 79 242 14 13 73 2 4 208 96 151 50 225 231 231 71] jsonWebKey:\u003cnil\u003e relativeURL:true multibaseEncoding:0} {ID:#key-2 Type:X25519KeyAgreementKey2019 Controller: Value:[71 163 184 58 201 45 86 212 112 87 251 226 124 211 114 220 12 245 71 208 124 232 163 62 31 234 52 57 7 142 170 70] jsonWebKey:\u003cnil\u003e relativeURL:true multibaseEncoding:0}] Service:[{ID:6c3f6a64-59aa-4fda-a9cf-1f32f9154600 Type:IndyAgent Priority:0 RecipientKeys:[did:key:z6MkswwjLRcD7hzQH5UgptFA8oryvHsLKaTXshLG5uoNiRo4] RoutingKeys:[] ServiceEndpoint:{rawDIDCommV2:[] rawDIDCommV1: rawObj:\u003cnil\u003e} Accept:[] Properties:map[] recipientKeysRelativeURL:map[] routingKeysRelativeURL:map[] relativeURL:false}] Authentication:[{VerificationMethod:{ID:#key-1 Type:Ed25519VerificationKey2018 Controller:#id Value:[200 129 16 160 162 169 62 155 40 146 165 154 66 226 43 92 206 79 242 14 13 73 2 4 208 96 151 50 225 231 231 71] jsonWebKey:\u003cnil\u003e relativeURL:true multibaseEncoding:0} Relationship:1 Embedded:false}] AssertionMethod:[{VerificationMethod:{ID:#key-1 Type:Ed25519VerificationKey2018 Controller:#id Value:[200 129 16 160 162 169 62 155 40 146 165 154 66 226 43 92 206 79 242 14 13 73 2 4 208 96 151 50 225 231 231 71] jsonWebKey:\u003cnil\u003e relativeURL:true multibaseEncoding:0} Relationship:2 Embedded:false}] CapabilityDelegation:[] CapabilityInvocation:[] KeyAgreement:[{VerificationMethod:{ID:#key-2 Type:X25519KeyAgreementKey2019 Controller: Value:[71 163 184 58 201 45 86 212 112 87 251 226 124 211 114 220 12 245 71 208 124 232 163 62 31 234 52 57 7 142 170 70] jsonWebKey:\u003cnil\u003e relativeURL:true multibaseEncoding:0} Relationship:5 Embedded:false}] Created:2022-06-02 02:03:13.023978529 +0000 UTC m=+34.592936212 Updated:2022-06-02 02:03:13.023978529 +0000 UTC m=+34.592936212 Proof:[] processingMeta:{baseURI:}}"}
```

**Comment by swcurran** [comment]
@Baha-sk -- any ideas?  Please let us know if it is something that needs to be done on the ACA-Py side to get this working.

**Comment by Moopli** [comment]
I'm working on this on the afgo side, I'll update you if I find anything that needs aca-py changes.

**Comment by Moopli** [comment]
@swcurran I got an error for you: Since we've added support for service endpoints being lists of objects, and I've updated the didcomm V2 service endpoints in afgo's public DIDs in AATH, aca-py now can't process the did docs:
```
aries_cloudagent.core.dispatcher ERROR Handler error: didx_create_request_implicit
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pydid/validation.py", line 13, in wrap_validation_error
    yield
  File "/usr/local/lib/python3.7/site-packages/pydid/resource.py", line 69, in deserialize
    return parse_obj_as(cls, value)
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for ParsingModel[DIDDocumentRoot]
__root__ -> service -> 2 -> serviceEndpoint
  expected string or bytes-like object (type=type_error)
__root__ -> service -> 2 -> serviceEndpoint
  str type expected (type=type_error.str)
__root__ -> service -> 2 -> serviceEndpoint
  unhashable type: 'list' (type=type_error)
```

**Comment by swcurran** [comment]
@shaangill025 -- can you please look into this as a high priority. I'd like to get the test harness running properly.  As needed, please create an issue in ACA-Py to track this.

FYI - @andrewwhitehead -- please weigh in if you have any guidance on this.

**Comment by andrewwhitehead** [comment]
This is actually happening inside @dbluhm 's pydid library

**Comment by dbluhm** [comment]
I'll look into this; thanks for the heads up
