### ISSUE TITLE
AFJ Test Agent Not starting with Askar and Indy VDR config errrors

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#658]
The AFJ agents are not starting. Example commands

```
./manage build -a javascript
LEDGER_URL_CONFIG=http://test.bcovrin.vonx.io TAILS_SERVER_URL_CONFIG=https://tails.vonx.io ./manage run -d javascript -n -t @RFC0160
```

Output logs:

```
using ngrok end point [bob_agent-ngrok]
Fetching end point from ngrok service
ngrok not ready, sleeping 5 seconds....
Fetching end point from ngrok service
fetched end point [https://64cc-96-54-62-211.ngrok.io]
Starting AFJ agent ...
[2K[1G[1myarn run v1.22.19[22m
[2K[1G[2m$ /src/node_modules/.bin/ts-node src/index.ts -p 9030 -i false[22m
/src/node_modules/ts-node/src/index.ts:744
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
[96msrc/TestAgent.ts[0m:[93m109[0m:[93m18[0m - [91merror[0m[90m TS2554: [0mExpected 1 arguments, but got 0.

[7m109[0m     anoncredsRs: new AnonCredsRsModule(),
[7m   [0m [91m                 ~~~~~~~~~~~~~~~~~~~~~~~[0m

  [96mnode_modules/@aries-framework/anoncreds-rs/build/AnonCredsRsModule.d.ts[0m:[93m6[0m:[93m17[0m
    [7m6[0m     constructor(config: AnonCredsRsModuleConfigOptions);
    [7m [0m [96m                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
    An argument for 'config' was not provided.
[96msrc/TestAgent.ts[0m:[93m110[0m:[93m32[0m - [91merror[0m[90m TS2345: [0mArgument of type '{ networks: [IndyVdrPoolConfig]; }' is not assignable to parameter of type 'IndyVdrModuleConfigOptions'.
  Property 'indyVdr' is missing in type '{ networks: [IndyVdrPoolConfig]; }' but required in type 'IndyVdrModuleConfigOptions'.

[7m110[0m     indyVdr: new IndyVdrModule({
[7m   [0m [91m                               ~[0m
[7m111[0m       networks: [indyNetworkConfig],
[7m   [0m [91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[7m112[0m     }),
[7m   [0m [91m~~~~~[0m

  [96mnode_modules/@aries-framework/indy-vdr/build/IndyVdrModuleConfig.d.ts[0m:[93m38[0m:[93m5[0m
    [7m38[0m     indyVdr: IndyVdr;
    [7m  [0m [96m    ~~~~~~~[0m
4:12[90m)[39m
    at reportTSError [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:748:19[90m)[39m
    at getOutput [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:935:36[90m)[39m
    at Object.compile [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:1237:30[90m)[39m
    at Module.m._compile [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:1364:30[90m)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)[39m
    at Object.require.extensions.<computed> [as .ts] [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:1368:12[90m)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:958:12)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)[39m {
  diagnosticText: [32m'\x1B[96msrc/TestAgent.ts\x1B[0m:\x1B[93m109\x1B[0m:\x1B[93m18\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2554: \x1B[0mExpected 1 arguments, but got 0.\n'[39m +
    [32m'\n'[39m +
    [32m'\x1B[7m109\x1B[0m     anoncredsRs: new AnonCredsRsModule(),\n'[39m +
    [32m'\x1B[7m   \x1B[0m \x1B[91m                 ~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n'[39m +
    [32m'\n'[39m +
    [32m'  \x1B[96mnode_modules/@aries-framework/anoncreds-rs/build/AnonCredsRsModule.d.ts\x1B[0m:\x1B[93m6\x1B[0m:\x1B[93m17\x1B[0m\n'[39m +
    [32m'    \x1B[7m6\x1B[0m     constructor(config: AnonCredsRsModuleConfigOptions);\n'[39m +
    [32m'    \x1B[7m \x1B[0m \x1B[96m                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n'[39m +
    [32m"    An argument for 'config' was not provided.\n"[39m +
    [32m"\x1B[96msrc/TestAgent.ts\x1B[0m:\x1B[93m110\x1B[0m:\x1B[93m32\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2345: \x1B[0mArgument of type '{ networks: [IndyVdrPoolConfig]; }' is not assignable to parameter of type 'IndyVdrModuleConfigOptions'.\n"[39m +
    [32m    'indyVdr' is declared here.
[96msrc/TestAgent.ts[0m:[93m116[0m:[93m12[0m - [91merror[0m[90m TS2554: [0mExpected 1 arguments, but got 0.

[7m116[0m     askar: new AskarModule(),
[7m   [0m [91m           ~~~~~~~~~~~~~~~~~[0m

  [96mnode_modules/@aries-framework/askar/build/AskarModule.d.ts[0m:[93m6[0m:[93m17[0m
    [7m6[0m     constructor(config: AskarModuleConfigOptions);
    [7m [0m [96m                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
    An argument for 'config' was not provided.

    at createTSError [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:74"  Property 'indyVdr' is missing in type '{ networks: [IndyVdrPoolConfig]; }' but required in type 'IndyVdrModuleConfigOptions'.\n"[39m +
    [32m'\n'[39m +
    [32m'\x1B[7m110\x1B[0m     indyVdr: new IndyVdrModule({\n'[39m +
    [32m'\x1B[7m   \x1B[0m \x1B[91m                               ~\x1B[0m\n'[39m +
    [32m'\x1B[7m111\x1B[0m       networks: [indyNetworkConfig],\n'[39m +
    [32m'\x1B[7m   \x1B[0m \x1B[91m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n'[39m +
    [32m'\x1B[7m112\x1B[0m     }),\n'[39m +
    [32m'\x1B[7m   \x1B[0m \x1B[91m~~~~~\x1B[0m\n'[39m +
    [32m'\n'[39m +
    [32m'  \x1B[96mnode_modules/@aries-framework/indy-vdr/build/IndyVdrModuleConfig.d.ts\x1B[0m:\x1B[93m38\x1B[0m:\x1B[93m5\x1B[0m\n'[39m +
    [32m'    \x1B[7m38\x1B[0m     indyVdr: IndyVdr;\n'[39m +
    [32m'    \x1B[7m  \x1B[0m \x1B[96m    ~~~~~~~\x1B[0m\n'[39m +
    [32m"    'indyVdr' is declared here.\n"[39m +
    [32m'\x1B[96msrc/TestAgent.ts\x1B[0m:\x1B[93m116\x1B[0m:\x1B[93m12\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2554: \x1B[0mExpected 1 arguments, but got 0.\n'[39m +
    [32m'\n'[39m +
    [32m'\x1B[7m116\x1B[0m     askar: new AskarModule(),\n'[39m +
    [32m'\x1B[7m   \x1B[0m \x1B[91m           ~~~~~~~~~~~~~~~~~\x1B[0m\n'[39m +
    [32m'\n'[39m +
    [32m'  \x1B[96mnode_modules/@aries-framework/askar/build/AskarModule.d.ts\x1B[0m:\x1B[93m6\x1B[0m:\x1B[93m17\x1B[0m\n'[39m +
    [32m'    \x1B[7m6\x1B[0m     constructor(config: AskarModuleConfigOptions);\n'[39m +
    [32m'    \x1B[7m \x1B[0m \x1B[96m                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n'[39m +
    [32m"    An argument for 'config' was not provided.\n"[39m,
  diagnosticCodes: [ [33m2554[39m, [33m2345[39m, [33m2554[39m ]
}
[2K[1G[31merror[39m Command failed with exit code 1.
[2K[1G[34minfo[39m Visit [1mhttps://yarnpkg.com/en/docs/cli/run[22m for documentation about this command.

```

**Comment by swcurran** [comment]
Fixed by #659
