### ISSUE TITLE
Indy VDR Typescript error preventing AFJ Agent from starting.

### ISSUE THREAD

**Issue by swcurran** [ianco/aries-agent-test-harness#669]
A new error has come up preventing the running of the AFJ Tests:

From the logs, after running command `./manage runset afj -b` (or `-r` if you want to build from scratch `--no-cache`):

```
Starting AFJ agent ...
[2K[1G[1myarn run v1.22.19[22m
[2K[1G[2m$ /src/node_modules/.bin/ts-node src/index.ts -p 9020 -i false[22m
/src/node_modules/ts-node/src/index.ts:744
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
[96msrc/TestAgent.ts[0m:[93m116[0m:[93m7[0m - [91merror[0m[90m TS2322: [0mType 'import("/src/node_modules/@hyperledger/indy-vdr-nodejs/node_modules/@hyperledger/indy-vdr-shared/build/types/IndyVdr").IndyVdr' is not assignable to type 'import("/src/node_modules/@hyperledger/indy-vdr-shared/build/types/IndyVdr").IndyVdr'.
  The types returned by 'requestGetBody(...)' are incompatible between these types.
    Type 'string' is not assignable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'string'.

[7m116[0m       indyVdr,
[7m   [0m [91m      ~~~~~~~[0m

  [96mnode_modules/@aries-framework/indy-vdr/build/IndyVdrModuleConfig.d.ts[0m:[93m38[0m:[93m5[0m
    [7m38[0m     indyVdr: IndyVdr;
    [7m  [0m [96m    ~~~~~~~[0m
    The expected type comes from property 'indyVdr' which is declared here on type 'IndyVdrModuleConfigOptions'

    at createTSError [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:744:12[90m)[39m
    at reportTSError [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:748:19[90m)[39m
    at getOutput [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:935:36[90m)[39m
    at Object.compile [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:1237:30[90m)[39m
    at Module.m._compile [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:1364:30[90m)[39m
[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)[39m
    at Object.require.extensions.<computed> [as .ts] [90m(/src/[39mnode_modules/[4mts-node[24m/src/index.ts:1368:12[90m)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:1117:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:958:12)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1141:19)[39m {
  diagnosticText: [32m`\x1B[96msrc/TestAgent.ts\x1B[0m:\x1B[93m116\x1B[0m:\x1B[93m7\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2322: \x1B[0mType 'import("/src/node_modules/@hyperledger/indy-vdr-nodejs/node_modules/@hyperledger/indy-vdr-shared/build/types/IndyVdr").IndyVdr' is not assignable to type 'import("/src/node_modules/@hyperledger/indy-vdr-shared/build/types/IndyVdr").IndyVdr'.\n`[39m +
    [32m"  The types returned by 'requestGetBody(...)' are incompatible between these types.\n"[39m +
    [32m"    Type 'string' is not assignable to type 'T'.\n"[39m +
    [32m"      'T' could be instantiated with an arbitrary type which could be unrelated to 'string'.\n"[39m +
    [32m'\n'[39m +
    [32m'\x1B[7m116\x1B[0m       indyVdr,\n'[39m +
    [32m'\x1B[7m   \x1B[0m \x1B[91m      ~~~~~~~\x1B[0m\n'[39m +
    [32m'\n'[39m +
    [32m'  \x1B[96mnode_modules/@aries-framework/indy-vdr/build/IndyVdrModuleConfig.d.ts\x1B[0m:\x1B[93m38\x1B[0m:\x1B[93m5\x1B[0m\n'[39m +
    [32m'    \x1B[7m38\x1B[0m     indyVdr: IndyVdr;\n'[39m +
    [32m'    \x1B[7m  \x1B[0m \x1B[96m    ~~~~~~~\x1B[0m\n'[39m +
    [32m"    The expected type comes from property 'indyVdr' which is declared here on type 'IndyVdrModuleConfigOptions'\n"[39m,
  diagnosticCodes: [ [33m2322[39m ]
}
[2K[1G[31merror[39m Command failed with exit code 1.
[2K[1G[34minfo[39m Visit [1mhttps://yarnpkg.com/en/docs/cli/run[22m for documentation about this command.


```

**Comment by swcurran** [comment]
@genaris @TimoGlastra
